name: new_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - images/bg1.jpeg
  - images/bg2.jpeg
  - images/bg3.jpeg
  - images/bg4.webp
  - images/bg5.jpeg
  - images/bg6.jpeg
  - images/bg7.jpg
  - images/bg8.jpeg
  - images/cover.jpeg
   
